# -*- coding: utf-8 -*-
"""single_layer_perceptron.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LMEzjVc-EPESxXnCMkyPZMTCFB1iCXmb
"""

train_csv_path = 'normalized_diabetes_train.csv'
test_csv_path = 'normalized_diabetes_test.csv'
df_train = pd.read_csv(train_csv_path)
df_test = pd.read_csv(test_csv_path)

x = np.arange(-10, 10, 0.1)
y = sigmoid(x)

plt.plot(x, y)
plt.title('Sigmoid Function')
plt.show()

# ¿Œ¡ˆ single layer_perceptron HW3